import GithubSlugger from "github-slugger";

import { SITE_BASE } from "../data/site";

const MARKDOWN_EXTENSION = ".md";
const README_BASENAME = "README";
const INDEX_CONTENT_ID = "index";
const NESTED_INDEX_PATTERN = /\/(?:index|readme)$/i;
const SAFE_SEGMENT_PATTERN = /^[A-Za-z0-9-]+$/;

export interface DocsStaticPath {
	params: {
		slug: string;
	};
	props: {
		contentId: string;
	};
}

function normalizeSegment(segment: string): string {
	if (segment === README_BASENAME) {
		return INDEX_CONTENT_ID;
	}

	if (SAFE_SEGMENT_PATTERN.test(segment)) {
		return segment;
	}

	const slugger = new GithubSlugger();
	return slugger.slug(segment);
}

export function sourcePathToContentId(sourcePath: string): string {
	return sourcePath
		.replace(/^docs\//, "")
		.split("/")
		.map((segment) =>
			segment.endsWith(MARKDOWN_EXTENSION)
				? segment.slice(0, -MARKDOWN_EXTENSION.length)
				: segment,
		)
		.map(normalizeSegment)
		.join("/");
}

export function contentIdToRoute(contentId: string): string {
	if (contentId === INDEX_CONTENT_ID) {
		return "/docs/";
	}

	if (NESTED_INDEX_PATTERN.test(contentId)) {
		return `/${contentId.replace(NESTED_INDEX_PATTERN, "")}/`;
	}

	return `/${contentId}/`;
}

export function createDocsStaticPaths(
	contentIds: readonly string[],
): DocsStaticPath[] {
	const contentIdByRoute = new Map<string, string>();
	const staticPaths: DocsStaticPath[] = [];

	for (const contentId of contentIds) {
		if (contentId === INDEX_CONTENT_ID) {
			continue;
		}

		const route = contentIdToRoute(contentId);
		const existingContentId = contentIdByRoute.get(route);
		if (existingContentId) {
			throw new Error(
				`Duplicate docs route "${route}" generated by content IDs "${existingContentId}" and "${contentId}".`,
			);
		}

		contentIdByRoute.set(route, contentId);
		staticPaths.push({
			params: {
				slug: route.replace(/^\/|\/$/g, ""),
			},
			props: {
				contentId,
			},
		});
	}

	return staticPaths;
}

export function withBase(pathname: string): string {
	const normalizedPathname =
		pathname === "/" || pathname.endsWith("/") ? pathname : `${pathname}/`;

	if (
		normalizedPathname === SITE_BASE ||
		normalizedPathname.startsWith(`${SITE_BASE}/`)
	) {
		return normalizedPathname;
	}

	if (normalizedPathname === "/") {
		return `${SITE_BASE}/`;
	}

	return `${SITE_BASE}${normalizedPathname}`;
}
