import { describe, expect, it } from "vitest";

import { createDocsStaticPaths } from "../../src/lib/routes";

describe("docs static routes", () => {
	it("normalizes nested README collection ids and excludes the root index", () => {
		const contentIds = [
			"index",
			"guide/agents/README",
			"guide/agents/architect-agent",
			"guide/harnesses/readme",
			"guide/harnesses/kiro-ide",
		] as const;

		expect(createDocsStaticPaths(contentIds)).toEqual([
			{
				params: { slug: "guide/agents" },
				props: { contentId: "guide/agents/README" },
			},
			{
				params: { slug: "guide/agents/architect-agent" },
				props: { contentId: "guide/agents/architect-agent" },
			},
			{
				params: { slug: "guide/harnesses" },
				props: { contentId: "guide/harnesses/readme" },
			},
			{
				params: { slug: "guide/harnesses/kiro-ide" },
				props: { contentId: "guide/harnesses/kiro-ide" },
			},
		]);
	});

	it("rejects content ids that normalize to the same static route", () => {
		expect(() =>
			createDocsStaticPaths([
				"guide/harnesses/README",
				"guide/harnesses/index",
			]),
		).toThrow(
			'Duplicate docs route "/guide/harnesses/" generated by content IDs "guide/harnesses/README" and "guide/harnesses/index".',
		);
	});
});
